name 'arussell-devenv'
version '0.0.1'
description 'Development environment, including IntelliJ IDEA'
author 'Adam Russell'
project_page 'https://bitbucket.org/arussell/puppet-devenv'
dependency 'puppetlabs/apt', '>= 1.4.0'
dependency 'smarchive/googlechrome', '>= 0.1.0'
dependency 'smarchive/idea', '>= 0.1.0'
dependency 'gini/gradle', '>= 0.2.0'
dependency 'softek/java7', '>= 0.1.0'
dependency 'puppetlabs/vcsrepo', '>= 0.2.0'
